language: php

php:
  - 7.3

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - mysql -e 'CREATE DATABASE laravel;'
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --no-interaction -vvv

script:
  - php artisan key:generate
  - vendor/bin/phpunit
